// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyko_ATRyKkYuOJsRJwnlmskXfPCXIvB4',
    appId: '1:919205389698:web:47de293ee7e86c53ea1b9b',
    messagingSenderId: '919205389698',
    projectId: 'reload-b5a16',
    authDomain: 'reload-b5a16.firebaseapp.com',
    storageBucket: 'reload-b5a16.appspot.com',
    measurementId: 'G-VHZNZ49CZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVzlbutS6tZQlPY60M-8izhuCPjlNYyhI',
    appId: '1:919205389698:android:03e53193a8a2438cea1b9b',
    messagingSenderId: '919205389698',
    projectId: 'reload-b5a16',
    storageBucket: 'reload-b5a16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxO6VpZZpIaK2cQeCuA-XxfE644rtMy8c',
    appId: '1:919205389698:ios:e31a0299fc205035ea1b9b',
    messagingSenderId: '919205389698',
    projectId: 'reload-b5a16',
    storageBucket: 'reload-b5a16.appspot.com',
    iosClientId: '919205389698-nf733dt6jatj6kpjfl0husomas198ckk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeFinderFireb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxO6VpZZpIaK2cQeCuA-XxfE644rtMy8c',
    appId: '1:919205389698:ios:e31a0299fc205035ea1b9b',
    messagingSenderId: '919205389698',
    projectId: 'reload-b5a16',
    storageBucket: 'reload-b5a16.appspot.com',
    iosClientId: '919205389698-nf733dt6jatj6kpjfl0husomas198ckk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeFinderFireb',
  );
}
